import { Content } from './types.ts';

export const COMPANY_INFO = {
    website: 'www.aahhoo.com',
    registerUrl: 'https://www.aahhoo.com/register/',
    memberUrl: 'https://www.aahhoo.com/member/',
    streamUrl: 'https://intrura.vhx.tv',
    booksUrl: 'https://amazon.com/author/josemoya',
    address: '1084 NW 135th CT, Miami, Fl 33182-2616. U.S.A.',
    phone: '+1 (305) 447 - 2699',
    fax: '+1 (305) 447 - 2699 , 2 , 7',
    email: 'info@aahhoo.com',
    whatsapp: '+1 (786) 564 - 4249',
    calendly: 'https://calendly.com/aahhoo/citas',
    mexicoPhone: '+52 55 4170 8006',
    socials: {
        yt: 'https://www.youtube.com/@drjosemoya',
        fb: 'https://www.facebook.com/drjmoya/',
        ig: 'https://www.instagram.com/aahhoo2go/',
        tt: 'https://www.tiktok.com/@drjmoya',
        x: 'https://x.com/pidasalud',
    }
};

const MORE_LINKS_DATA = [
    { icon: 'ArticleIcon', url: 'https://aahhoo.com/a/', en: { title: 'Articles', description: 'In-depth articles and resources.' }, es: { title: 'Artículos', description: 'Artículos y recursos detallados.' }},
    { icon: 'ReelIcon', url: 'https://aahhoo.com/r/', en: { title: 'Reels', description: 'Watch our latest short videos.' }, es: { title: 'Reels', description: 'Mira nuestros últimos videos cortos.' }},
    { icon: 'ReelAdminIcon', url: 'https://reeladmin.com/index.html', en: { title: 'Request a Reel', description: 'Request custom reels for your networks.' }, es: { title: 'Solicita un Reel', description: 'Solicita reels personalizados para tus redes.' }},
    { icon: 'VideoIcon', url: 'https://aahhoo.com/vid/', en: { title: 'Specific Videos', description: 'Find specific videos on our platform.' }, es: { title: 'Videos Específicos', description: 'Encuentra videos en nuestra plataforma.' }},
    { icon: 'AudioIcon', url: 'https://oyeleeve.com/', en: { title: 'Audios', description: 'Listen to our audio content.' }, es: { title: 'Audios', description: 'Escucha nuestro contenido de audio.' }},
    { icon: 'PodcastIcon', url: 'https://open.spotify.com/show/2ulPvbXVQt4EkWAKJprAx7', en: { title: 'Podcast', description: 'Tune into our Spotify podcast.' }, es: { title: 'Podcast', description: 'Sintoniza nuestro podcast en Spotify.' }},
    { icon: 'YouTubeIcon', url: 'https://www.youtube.com/@drjosemoya', en: { title: 'YouTube Channel', description: 'Subscribe to our official channel.' }, es: { title: 'Canal de YouTube', description: 'Suscríbete a nuestro canal oficial.' }},
    { icon: 'XIcon', url: 'https://x.com/pidasalud', en: { title: 'X (Twitter)', description: 'Follow us for live updates.' }, es: { title: 'X (Twitter)', description: 'Síguenos para actualizaciones en vivo.' }},
    { icon: 'FacebookIcon', url: 'https://www.facebook.com/nomasvitiligo', en: { title: 'Facebook (Vitiligo)', description: 'Join our community on Vitiligo.' }, es: { title: 'Facebook (Vitiligo)', description: 'Únete a nuestra comunidad sobre Vitiligo.' }},
    { icon: 'FacebookIcon', url: 'https://www.facebook.com/drjmoya/', en: { title: 'Facebook (Dr. Moya)', description: 'Connect with Dr. Jose Moya.' }, es: { title: 'Facebook (Dr. Moya)', description: 'Conecta con el Dr. Jose Moya.' }},
    { icon: 'InstagramIcon', url: 'https://www.instagram.com/aahhoo2go/', en: { title: 'Instagram', description: 'Follow our visual stories.' }, es: { title: 'Instagram', description: 'Sigue nuestras historias visuales.' }},
    { icon: 'TikTokIcon', url: 'https://www.tiktok.com/@drjmoya', en: { title: 'TikTok', description: 'Watch our latest trends and tips.' }, es: { title: 'TikTok', description: 'Mira nuestras últimas tendencias y consejos.' }},
];

export const content: Content = {
  en: {
    tagline: 'A superior quality of life, within your reach.',
    heroSubtitle: 'Inclusive events near you to earn extra while helping others to excel. Make it yours now!',
    aboutTitle: 'Our Global Presence',
    aboutText: 'We hold planned events in various cities and countries. Meetings take place at Marriott hotels or similar venues and in Regus offices, with over 3,000 locations available in more than 150 countries, all central, well-located, and secure. These events are scheduled promptly, with availability within the current month.',
    servicesTitle: 'Our Services & Products',
    services: [
      { title: 'Quality of Life Conferences', description: 'Dedicated to improving quality of life, finding new employment, and managing chronic inflammatory health conditions like Psoriasis, Vitiligo, Allergies, Arthritis, and over 300 others.' },
      { title: 'Genome Sequencing Analysis', description: 'We obtain a saliva sample and provide over 100 genetic reports for a deep understanding of your health.' },
      { title: 'Protocol for Vitiligo', description: 'We offer a complete protocol with specialized creams for year-round skin care.' },
      { title: 'Medical Equipment Sales and Rentals', description: 'We offer equipment for sale and rent to manage many diseases from the comfort of your home.' },
      { title: 'Training and Professional Network', description: 'We train family members and doctors, adding them to our global support network as representatives and associates.' },
      { title: 'Application Development', description: 'We develop and manage custom applications for our associates, enhancing their reach and practice.' },
      { title: 'Concierge Doctor Program', description: 'Personalized assistance and high-precision functional medicine for an unparalleled health experience.' },
    ],
    locationsTitle: 'Our Global Headquarters',
    locationsSubtitle: 'We conduct our events at premier locations worldwide, ensuring a professional, safe, and accessible experience. Here are some examples of our available venues.',
    locations: [
      { city: 'New York', addresses: ['245 Park Avenue, 39th Floor', '100 Park Avenue, 16th Floor'] },
      { city: 'Miami', addresses: ['201 South Biscayne Blvd, 28th Floor', '801 Brickell Avenue, Suite 900'] },
      { city: 'London', addresses: ['1 Kingdom Street, Paddington', 'Canary Wharf, 30th Floor'] },
      { city: 'Madrid', addresses: ['Paseo de la Castellana, 93', 'Torre de Cristal, Paseo de la Castellana, 259C'] },
      { city: 'Mexico City', addresses: ['Paseo de la Reforma 265', 'Insurgentes Sur 859, Piso 2'] },
      { city: 'Paris', addresses: ["14 Avenue de l'Opéra", 'Tour First, 1 Place des Saisons'] },
      { city: 'Panama City', addresses: ['Sortis Business Tower, Calle 56 y 57', 'Torre de Las Americas, Punta Pacifica'] },
    ],
    associatesTitle: 'Meet Our Global Associates',
    associatesSubtitle: 'Our strength lies in our international network of dedicated professionals. We are proud to introduce some of our associates. Join us and become part of this growing team.',
    associates: [
        { name: 'Dr. Elena Vance', location: 'New York, USA' },
        { name: 'Carlos Gutierrez', location: 'Mexico City, Mexico' },
        { name: 'Sophie Dubois', location: 'Paris, France' },
        { name: 'Javier Castillo', location: 'Madrid, Spain' },
        { name: 'Isabella Rossi', location: 'Rome, Italy' },
        { name: 'Kenji Tanaka', location: 'Tokyo, Japan' },
        { name: 'Liam Smith', location: 'London, UK' },
        { name: 'Sofia Andrade', location: 'Panama City, Panama' },
    ],
    externalLinksTitle: 'Discover More',
    streamTitle: 'AAHHOO Stream',
    streamText: 'Access our exclusive library of streaming content.',
    booksTitle: 'Author Books',
    booksText: 'Explore the collection of books by our founder.',
    moreLinksTitle: 'Our Channels',
    moreLinksSubtitle: 'Connect with us on our different platforms and social networks.',
    moreLinks: [
      { title: 'YouTube', url: COMPANY_INFO.socials.yt, description: 'Follow our official video channel.', icon: 'YouTubeIcon' },
      { title: 'Facebook', url: COMPANY_INFO.socials.fb, description: 'Join our community on Facebook.', icon: 'FacebookIcon' },
      { title: 'Instagram', url: COMPANY_INFO.socials.ig, description: 'Visual inspiration on Instagram.', icon: 'InstagramIcon' },
      { title: 'TikTok', url: COMPANY_INFO.socials.tt, description: 'Creative content on TikTok.', icon: 'TikTokIcon' },
      { title: 'X (Twitter)', url: COMPANY_INFO.socials.x, description: 'Updates and news on X.', icon: 'XIcon' },
    ],
    exploreMoreTitle: 'Explore More',
    exploreMoreLinks: MORE_LINKS_DATA.map(link => ({
        icon: link.icon,
        url: link.url,
        title: link.en.title,
        description: link.en.description,
    })),
    contactTitle: 'Contact Us',
    investmentPrice: 'For investment price: Please call local numbers or contact us via WhatsApp.',
    bookingLink: 'Book an Appointment',
    callToAction: 'Learn More',
    loginText: 'Member Login',
    registerText: 'Register',
    footerRights: 'All rights reserved',
  },
  es: {
    tagline: 'Una calidad de vida superior, a tu alcance.',
    heroSubtitle: 'Eventos inclusivos cerca de ti para ganar un extra mientras ayudas a otros a superarse. ¡Hazlo tuyo ahora!',
    aboutTitle: 'Nuestra Presencia Global',
    aboutText: 'Hacemos eventos planificados en otras ciudades y países. Las reuniones se realizan en hoteles Marriott o similares y en oficinas Regus, con más de 3000 oficinas disponibles en más de 150 países, céntricas, bien localizadas y seguras. Estos eventos se planifican de inmediato, con disponibilidad en el mismo mes en curso.',
    servicesTitle: 'Nuestros Servicios y Productos',
    services: [
      { title: 'Conferencias de Calidad de Vida', description: 'Dedicadas a mejorar la calidad de vida, nuevos empleos y controlar condiciones de salud con inflamación crónica como Psoriasis, Vitiligo, Alergias, Artritis y más de 300 otras.' },
      { title: 'Análisis de Secuenciación del Genoma', description: 'Obtenemos una muestra de saliva y ofrecemos más de 100 reportes genéticos para un profundo conocimiento de su salud.' },
      { title: 'Protocolo para el Vitiligo', description: 'Ofrecemos un protocolo completo con cremas especializadas para el cuidado de la piel durante todo el año.' },
      { title: 'Venta y Renta de Equipos Médicos', description: 'Ofrecemos equipos para la venta y renta para controlar muchas enfermedades desde la comodidad de su hogar.' },
      { title: 'Entrenamiento y Red Profesional', description: 'Entrenamos a familiares y médicos, añadiéndolos a nuestra red de asistencia global como representantes y asociados.' },
      { title: 'Desarrollo de Aplicaciones', description: 'Desarrollamos y administramos aplicaciones personalizadas para nuestros asociados, mejorando su alcance y práctica.' },
      { title: 'Programa de Concierge Doctor', description: 'Asistencia personalizada y medicina funcional de elevada precisión para una experiencia de salud inigualable.' },
    ],
    locationsTitle: 'Nuestras Sedes Globales',
    locationsSubtitle: 'Realizamos nuestros eventos en ubicaciones de primer nivel en todo el mundo, garantizando una experiencia profesional, segura y accesible. Aquí hay algunos ejemplos de nuestras sedes disponibles.',
    locations: [
        { city: 'New York', addresses: ['245 Park Avenue, 39th Floor', '100 Park Avenue, 16th Floor'] },
        { city: 'Miami', addresses: ['201 South Biscayne Blvd, 28th Floor', '801 Brickell Avenue, Suite 900'] },
        { city: 'London', addresses: ['1 Kingdom Street, Paddington', 'Canary Wharf, 30th Floor'] },
        { city: 'Madrid', addresses: ['Paseo de la Castellana, 93', 'Torre de Cristal, Paseo de la Castellana, 259C'] },
        { city: 'Mexico City', addresses: ['Paseo de la Reforma 265', 'Insurgentes Sur 859, Piso 2'] },
        { city: 'Paris', addresses: ["14 Avenue de l'Opéra", 'Tour First, 1 Place des Saisons'] },
        { city: 'Panama City', addresses: ['Sortis Business Tower, Calle 56 y 57', 'Torre de Las Americas, Punta Pacifica'] },
    ],
    associatesTitle: 'Conozca a Nuestros Asociados Globales',
    associatesSubtitle: 'Nuestra fortaleza reside en nuestra red internacional de profesionales dedicados. Nos enorgullece presentar a algunos de nuestros asociados. Únase a nosotros y forme parte de este equipo en crecimiento.',
    associates: [
        { name: 'Dr. Elena Vance', location: 'New York, USA' },
        { name: 'Carlos Gutierrez', location: 'Mexico City, Mexico' },
        { name: 'Sophie Dubois', location: 'Paris, France' },
        { name: 'Javier Castillo', location: 'Madrid, Spain' },
        { name: 'Isabella Rossi', location: 'Rome, Italy' },
        { name: 'Kenji Tanaka', location: 'Tokyo, Japan' },
        { name: 'Liam Smith', location: 'London, UK' },
        { name: 'Sofia Andrade', location: 'Panama City, Panama' },
    ],
    externalLinksTitle: 'Descubre Más',
    streamTitle: 'AAHHOO Stream',
    streamText: 'Accede a nuestra biblioteca exclusiva de contenido en streaming.',
    booksTitle: 'Libros del Autor',
    booksText: 'Explora la colección de libros de nuestro fundador.',
    moreLinksTitle: 'Nuestros Canales',
    moreLinksSubtitle: 'Conecta con nosotros en nuestras diferentes plataformas y redes sociales.',
    moreLinks: [
        { title: 'YouTube', url: COMPANY_INFO.socials.yt, description: 'Sigue nuestro canal de video oficial.', icon: 'YouTubeIcon' },
        { title: 'Facebook', url: COMPANY_INFO.socials.fb, description: 'Únete a nuestra comunidad en Facebook.', icon: 'FacebookIcon' },
        { title: 'Instagram', url: COMPANY_INFO.socials.ig, description: 'Inspiración visual en Instagram.', icon: 'InstagramIcon' },
        { title: 'TikTok', url: COMPANY_INFO.socials.tt, description: 'Contenido creativo en TikTok.', icon: 'TikTokIcon' },
        { title: 'X (Twitter)', url: COMPANY_INFO.socials.x, description: 'Actualizaciones y noticias en X.', icon: 'XIcon' },
    ],
    exploreMoreTitle: 'Explora Más',
    exploreMoreLinks: MORE_LINKS_DATA.map(link => ({
        icon: link.icon,
        url: link.url,
        title: link.es.title,
        description: link.es.description,
    })),
    contactTitle: 'Contáctanos',
    investmentPrice: 'Precio por inversión: Llamar a teléfonos locales o WhatsApp.',
    bookingLink: 'Agendar una Cita',
    callToAction: 'Saber Más',
    loginText: 'Miembros',
    registerText: 'Registrarse',
    footerRights: 'Todos los derechos reservados',
  },
};
